scalecube/scalecube-cluster

pom.xml
travis-settings.xml

Please verify that the snapshot version is deployed to sonatype nexus snapshots repo BEFORE merging this one

Release next version

---

.travis.yml

removed slack secret
alignment to codacy coverage reporter command

Fix integrations

---

transport/src/main/java/io/scalecube/transport/Addressing.java
transport/src/main/java/io/scalecube/transport/TransportConfig.java
transport/src/main/java/io/scalecube/transport/TransportImpl.java

bind to port 0 by default to speed tests.

---

cluster/src/main/java/io/scalecube/cluster/ClusterConfig.java
cluster/src/test/java/io/scalecube/cluster/fdetector/FailureDetectorTest.java
cluster/src/test/java/io/scalecube/cluster/gossip/GossipProtocolTest.java
examples/src/main/java/io/scalecube/examples/ClusterJoinExamples.java
transport/src/main/java/io/scalecube/transport/Addressing.java
transport/src/main/java/io/scalecube/transport/TransportConfig.java
transport/src/main/java/io/scalecube/transport/TransportImpl.java
transport/src/test/java/io/scalecube/transport/TransportSendOrderTest.java
transport/src/test/java/io/scalecube/transport/TransportTest.java
transport/src/test/java/io/scalecube/transport/TransportTestUtils.java

Fix to https://github.com/scalecube/scalecube-cluster/issues/26

Get rid of port-auto-increment

---

cluster/src/main/java/io/scalecube/cluster/gossip/GossipProtocolImpl.java

Fixed removing member after update its metadata

---

cluster/src/main/java/io/scalecube/cluster/fdetector/FailureDetectorImpl.java
cluster/src/main/java/io/scalecube/cluster/gossip/GossipProtocolImpl.java
cluster/src/main/java/io/scalecube/cluster/membership/MembershipProtocolImpl.java

Fixed https://github.com/scalecube/scalecube-services/issues/428

Fixed ErrorCallbackNotImplemented

---

transport/src/main/java/io/scalecube/transport/TransportImpl.java

Changed max frame length

---

cluster/src/main/java/io/scalecube/cluster/membership/MembershipProtocolImpl.java
cluster/src/test/java/io/scalecube/cluster/ClusterTest.java
transport/src/main/java/io/scalecube/transport/Address.java

Fixes https://github.com/scalecube/scalecube-cluster/issues/109

Added test on joining to localhost

---

cluster/src/main/java/io/scalecube/cluster/ClusterImpl.java
cluster/src/main/java/io/scalecube/cluster/gossip/GossipProtocolImpl.java
cluster/src/main/java/io/scalecube/cluster/membership/MembershipProtocol.java
cluster/src/main/java/io/scalecube/cluster/membership/MembershipProtocolImpl.java

Fixes https://github.com/scalecube/scalecube-cluster/issues/116

Improve membership event handling

---

cluster/src/main/java/io/scalecube/cluster/gossip/GossipProtocolImpl.java
cluster/src/main/java/io/scalecube/cluster/gossip/GossipRequest.java

Fix for Support batches for gossips #128

---

cluster/src/main/java/io/scalecube/cluster/Cluster.java
cluster/src/main/java/io/scalecube/cluster/ClusterImpl.java

allow to delete metadata property
```java
cluster.removeMetadataProperty("some-key");
```

add remove metadata property

---

cluster/src/test/java/io/scalecube/cluster/ClusterTest.java

allow to delete metadata property
```java
cluster.removeMetadataProperty("some-key");
```

add remove property test

---

cluster/src/main/java/io/scalecube/cluster/Cluster.java
cluster/src/main/java/io/scalecube/cluster/ClusterImpl.java
transport/src/main/java/io/scalecube/transport/Transport.java
transport/src/main/java/io/scalecube/transport/TransportImpl.java
transport/src/test/java/io/scalecube/transport/TransportTest.java

Add Request response communication pattern in transport and cluster

add request response

---

cluster/src/main/java/io/scalecube/cluster/membership/MembershipProtocolImpl.java

Fixes #130
Fixes https://github.com/scalecube/scalecube-cluster/issues/115

Fuixed issue #130

---

cluster/src/main/java/io/scalecube/cluster/ClusterMath.java
cluster/src/test/java/io/scalecube/cluster/membership/MembershipProtocolTest.java

Fixes https://github.com/scalecube/scalecube-cluster/issues/137

Improve test cluster config and timeouts for test. Fixes #137.

---

cluster/src/main/java/io/scalecube/cluster/ClusterConfig.java
cluster/src/test/java/io/scalecube/cluster/gossip/GossipRequestTest.java
transport/src/main/java/io/scalecube/transport/JacksonMessageCodec.java
transport/src/main/java/io/scalecube/transport/MessageCodec.java
transport/src/main/java/io/scalecube/transport/TransportConfig.java
transport/src/main/java/io/scalecube/transport/TransportImpl.java

I want to use other type of serialization but can't because that mechanism inlined.

Added abstraction over serialization

---

cluster/src/main/java/io/scalecube/cluster/fdetector/FailureDetectorImpl.java
cluster/src/main/java/io/scalecube/cluster/gossip/GossipProtocolImpl.java

Changed work with period in FailureDetectorImpl and GossipProtocolImpl

---

cluster/src/main/java/io/scalecube/cluster/ClusterConfig.java

Simplified output of metadata in toString of the cluster config

---

cluster/src/main/java/io/scalecube/cluster/membership/MembershipProtocolImpl.java
cluster/src/test/java/io/scalecube/cluster/ClusterTest.java

Closes https://github.com/scalecube/scalecube-cluster/issues/199

Got rid of Sink in MembershipProtocolImpl#start0

---

cluster-api/src/main/java/io/scalecube/cluster/ClusterConfig.java
cluster-api/src/main/java/io/scalecube/cluster/fdetector/FailureDetectorConfig.java
cluster-api/src/main/java/io/scalecube/cluster/gossip/GossipConfig.java
cluster-api/src/main/java/io/scalecube/cluster/membership/MembershipConfig.java
cluster/src/main/java/io/scalecube/cluster/ClusterImpl.java
cluster/src/main/java/io/scalecube/cluster/fdetector/FailureDetectorImpl.java
cluster/src/main/java/io/scalecube/cluster/gossip/GossipProtocolImpl.java
cluster/src/main/java/io/scalecube/cluster/membership/MembershipProtocolImpl.java
cluster/src/main/java/io/scalecube/cluster/metadata/MetadataStoreImpl.java
cluster/src/test/java/io/scalecube/cluster/BaseTest.java
cluster/src/test/java/io/scalecube/cluster/ClusterTest.java
cluster/src/test/java/io/scalecube/cluster/fdetector/FailureDetectorTest.java
cluster/src/test/java/io/scalecube/cluster/gossip/GossipProtocolTest.java
cluster/src/test/java/io/scalecube/cluster/membership/MembershipProtocolTest.java
examples/src/main/java/io/scalecube/examples/ClusterJoinExamples.java
examples/src/main/java/io/scalecube/examples/ClusterMetadataExample.java
examples/src/main/java/io/scalecube/examples/GossipExample.java
examples/src/main/java/io/scalecube/examples/MembershipEventsExample.java
examples/src/main/java/io/scalecube/examples/MessagingExample.java
examples/src/main/java/io/scalecube/issues/i187/NodeIthRunner.java
examples/src/main/java/io/scalecube/issues/i187/NodeNoInboundRunner.java
examples/src/main/java/io/scalecube/issues/i187/SeedRunner.java
transport-parent/transport-api/src/main/java/io/scalecube/cluster/transport/api/TransportConfig.java
transport-parent/transport-netty/src/main/java/io/scalecube/transport/netty/TransportImpl.java

Fixes https://github.com/scalecube/scalecube-cluster/issues/202

Refactor configuration approach

---

cluster-api/src/main/java/io/scalecube/cluster/Cluster.java
cluster/src/main/java/io/scalecube/cluster/ClusterImpl.java
cluster/src/test/java/io/scalecube/cluster/ClusterTest.java
examples/src/main/java/io/scalecube/examples/MembershipEventsExample.java

Fixes https://github.com/scalecube/scalecube-cluster/issues/200

Added `Mono onShutdown()` method, made shutdown() to be `void`

---

cluster/src/test/java/io/scalecube/cluster/membership/MembershipProtocolTest.java

Fixes #221 
Replaced waiting by some time to waiting for when the expected event will happen + added timeout for it.

Fixed unstable `testRestartStoppedMembers` test

---

cluster-api/src/main/java/io/scalecube/cluster/ClusterConfig.java

Fixe to issue #238  (shortcut methods in ClusterConfig)

---

cluster-api/src/main/java/io/scalecube/cluster/gossip/GossipConfig.java
cluster/src/main/java/io/scalecube/cluster/gossip/Gossip.java
cluster/src/main/java/io/scalecube/cluster/gossip/GossipProtocolImpl.java
cluster/src/main/java/io/scalecube/cluster/gossip/SequenceIdCollector.java
cluster/src/test/java/io/scalecube/cluster/gossip/GossipDelayTest.java
cluster/src/test/java/io/scalecube/cluster/gossip/GossipRequestTest.java
cluster/src/test/java/io/scalecube/cluster/gossip/SequenceIdCollectorTest.java

Fix outdated repeated gossip using data structure which efficiently store sequence of incremented numbers(gossip sequenceId) which go in a row without missed elements. Each gossip will be checked  that it was handled before. 
#263

Fix outdated repeated gossip

---

cluster/src/test/java/io/scalecube/cluster/ClusterTest.java

**Motivation**
Trying reproduce issue https://github.com/scalecube/scalecube-cluster/issues/280

Added test on repeated start stop of cluster instance

---

cluster/src/main/java/io/scalecube/cluster/ClusterImpl.java

Fixed issues with not-unregistering mbean

---

cluster/src/test/java/io/scalecube/cluster/membership/MembershipProtocolTest.java
pom.xml

As part of updating rsocket version in https://github.com/scalecube/scalecube-services/pull/761

Update reactor versions

---

cluster-api/src/main/java/io/scalecube/cluster/Member.java
pom.xml

* Changed member toStrign
* Cleanup pom

Change member to string format

---

transport-parent/transport-api/src/main/java/io/scalecube/cluster/transport/api/TransportConfig.java
transport-parent/transport-netty/src/main/java/io/scalecube/transport/netty/TransportImpl.java
transport-parent/transport-netty/src/main/java/io/scalecube/transport/netty/tcp/TcpReceiver.java
transport-parent/transport-netty/src/main/java/io/scalecube/transport/netty/tcp/TcpSender.java
transport-parent/transport-netty/src/main/java/io/scalecube/transport/netty/tcp/TcpTransportFactory.java
transport-parent/transport-netty/src/main/java/io/scalecube/transport/netty/websocket/WebsocketReceiver.java
transport-parent/transport-netty/src/main/java/io/scalecube/transport/netty/websocket/WebsocketSender.java
transport-parent/transport-netty/src/main/java/io/scalecube/transport/netty/websocket/WebsocketTransportFactory.java

Allow alternative transport implementations to reuse the existing Websocket* classes.

Alternative transport implementations

---

.github/workflows/branch-ci.yml
.github/workflows/pre-release-ci.yml
.github/workflows/release-ci.yml
checkstyle-suppressions.xml
cluster-testlib/src/main/java/io/scalecube/cluster/utils/NetworkEmulator.java
cluster-testlib/src/test/java/io/scalecube/cluster/utils/BaseTest.java
cluster/pom.xml
cluster/src/main/java/io/scalecube/cluster/ClusterImpl.java
cluster/src/main/java/io/scalecube/cluster/fdetector/FailureDetectorImpl.java
cluster/src/main/java/io/scalecube/cluster/gossip/GossipProtocolImpl.java
cluster/src/main/java/io/scalecube/cluster/membership/MembershipProtocolImpl.java
cluster/src/main/java/io/scalecube/cluster/metadata/MetadataStoreImpl.java
cluster/src/test/java/io/scalecube/cluster/BaseTest.java
cluster/src/test/java/io/scalecube/cluster/ClusterTest.java
cluster/src/test/java/io/scalecube/cluster/gossip/GossipProtocolTest.java
examples/pom.xml
pom.xml
transport-parent/pom.xml
transport-parent/transport-netty/src/main/java/io/scalecube/transport/netty/TransportImpl.java
transport-parent/transport-netty/src/test/java/io/scalecube/transport/netty/BaseTest.java
transport-parent/transport-netty/src/test/java/io/scalecube/transport/netty/tcp/TcpTransportSendOrderTest.java
transport-parent/transport-netty/src/test/java/io/scalecube/transport/netty/tcp/TcpTransportTest.java
transport-parent/transport-netty/src/test/java/io/scalecube/transport/netty/websocket/WebsocketTransportSendOrderTest.java
transport-parent/transport-netty/src/test/java/io/scalecube/transport/netty/websocket/WebsocketTransportTest.java

Changes: 
* Set new parent (with jdk 17).
* Updated CI yaml files.
* Removed slf4j from dependencies.
* Cleanup poms.
* Bump `jackson` to `2.18.0`.

Upgrade to jdk17 and cleanup

---

.github/workflows/pre-release-ci.yml
.github/workflows/release-ci.yml
cluster-api/pom.xml
cluster-testlib/pom.xml
cluster/pom.xml
codec-parent/pom.xml
examples/pom.xml
pom.xml
transport-parent/pom.xml

Bump dependencies:
scalecube-parent -> 0.3.12
reactor -> 2024.0.8
jackson -> 2.19.2

Bump dependencies
